version: "3.9"

services:
  redis:
    image: "redis:alpine"

  # db:
  #   image: mariadb
  #   restart: always
  #   volumes:
  #     - database:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: django-db
  #     MYSQL_ROOT_PASSWORD: django-root
  #     MYSQL_PASSWORD: django-pass
  #     MYSQL_USER: django
  app:
    image: justereseau/beer-scanner:latest
    build: ./app
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: django-db
      MYSQL_PASSWORD: django-pass
      MYSQL_USER: django
      DJANGO_SECRET_KEY: ChangeThisWhenInProd
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./data:/data
      - ./io:/io
      - ./app/app_manager:/app/app_manager:ro
      - ./app/drink_consumption:/app/drink_consumption:ro
