version: "3.9"

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: django-db
      MYSQL_ROOT_PASSWORD: django-root
      MYSQL_PASSWORD: django-pass
      MYSQL_USER: django
  web:
    image: justereseau/beer-scanner:latest
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: django-db
      MYSQL_PASSWORD: django-pass
      MYSQL_USER: django
      DJANGO_SECRET_KEY: ChangeThisWhenInProd
    ports:
      - "8000:8000"
    depends_on:
      - db
